version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: university-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: university
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/university?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appsecret
    stdin_open: true
    tty: true
    command: ["./gradlew", "bootRun"]

volumes:
  db_data:
